# Generated by Django 5.1.2 on 2024-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='comp.category'),
        ),
    ]
