# Generated by Django 5.1.2 on 2024-10-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/mercedes-amg-gt-43-coupe-2024.jpg', upload_to='images/'),
        ),
    ]
